### ISSUE TITLE
Yahoo API says "html table is no longer supported."

### ISSUE THREAD

**Issue by Quramy** [yoshiko-pg/connpass-card#14]
😱 

![-_name_cards_generator_for_events](https://user-images.githubusercontent.com/1262998/26908497-e7ac6d5c-4c35-11e7-86bd-1294363aaf73.png)

Can't fetch event-page HTML...

**Comment by yoshiko-pg** [comment]
そうなんですよお 😭 
まだお知らせのツイートしかできてなく・・・とりあえず今週中にはどっかサーバー用意しようかと 😭 
ただ今週仕事がぱつってて、土曜日になってしまうかもです。。

**Comment by Quramy** [comment]
あ、既知の問題だったのですね... 💦 

> ただ今週仕事がぱつってて、土曜日になってしまうかもです。。

お疲れ様です...!

**Comment by yoshiko-pg** [comment]
とりあえずHeadwayにお知らせ投稿しました！
昨日知りました〜 😭 
issueありがとうございます！このまま使わせていただきます！

**Comment by Quramy** [comment]
> どっかサーバー用意しようかと

ふと思っただけなんですけど、DOMをfetchできればよいのであれば、Lambdaとかでもよいかも？

**Comment by yoshiko-pg** [comment]
AWS Lambdaですか？詳しく知りたいです＞＜

**Comment by Quramy** [comment]
そうですそうですー。

このappの場合、殆どHTTP requestだけ肩代わりしてくれるserviceがあれば必要十分なので、AWS Lambdaは使えそう。生でLambda を使うのは結構面倒ですけど、 https://serverless.com/framework/docs/ とか使えば、簡単にdeployまでできますし。

明日仕事休みだし、折角なので僕もちょっとトライしてみます。

**Comment by yoshiko-pg** [comment]
ほわあああ😭ありがとうございます😭😭😭
わたしも土曜日に見てみます！！
